version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s %(version)s %(message)s %(extra)s'
  json:
    class: LoggingJsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(version)s %(message)s %(extra)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
root:
  level: INFO
  handlers: [console]