version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s %(version)s %(message)s'
  json:
    class: logging_mv_integrations.logging_json_formatter.LoggingJsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(version)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
root:
  level: INFO
  handlers: [console]